CREATE OR REPLACE PROCEDURE AUTOMATED_INTELLIGENCE.AUDITOR.RUN_DUE_AUDITS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  LET due_count INTEGER := (
    SELECT COUNT(*)
    FROM AUTOMATED_INTELLIGENCE.AUDITOR.AUDIT_SCHEDULES
    WHERE ENABLED = TRUE
      AND NEXT_RUN <= CURRENT_TIMESTAMP()
  );

  UPDATE AUTOMATED_INTELLIGENCE.AUDITOR.AUDIT_SCHEDULES
  SET LAST_RUN = CURRENT_TIMESTAMP(),
      LAST_STATUS = 'running',
      NEXT_RUN = DATEADD('minute', INTERVAL_MINUTES, CURRENT_TIMESTAMP())
  WHERE ENABLED = TRUE
    AND NEXT_RUN <= CURRENT_TIMESTAMP();

  RETURN 'Processed ' || :due_count || ' due audit(s)';
END;
$$
